import '../../test.dart';

void main() {
  group('Song sorting', () {
    late List<Song> songs;
    setUp(() {
      songs = [
        songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
        songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
        songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
        songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
        songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
        songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
        songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
        songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
        songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
        songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
        songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
        songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
        songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
        songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
        songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
        songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
        songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
        songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
        songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
        songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
        songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
        songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
        songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
        songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
        songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
        songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
        songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
        songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
        songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
      ];
    });
    final Map<SortOrder, Map<SongSortFeature, List<Song>>> testCases = {
      SortOrder.ascending: {
        SongSortFeature.dateModified: [
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
        ],
        SongSortFeature.dateAdded: [
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
        ],
        SongSortFeature.title: [
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
        ],
        SongSortFeature.artist: [
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
        ],
        SongSortFeature.album: [
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
        ],
      },
      SortOrder.descending: {
        SongSortFeature.dateModified: [
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
        ],
        SongSortFeature.dateAdded: [
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
        ],
        SongSortFeature.title: [
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
        ],
        SongSortFeature.artist: [
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
        ],
        SongSortFeature.album: [
          songWith(id: 28, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'я (кириллица)'),
          songWith(id: 26, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'АА (кириллица)'),
          songWith(id: 25, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'А (кириллица)'),
          songWith(id: 27, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'а (кириллица)'),
          songWith(id: 16, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'z'),
          songWith(id: 14, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'AA'),
          songWith(id: 13, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'A'),
          songWith(id: 15, dateModified: 0, dateAdded: 0, title: '', artist: '', album: 'a'),
          songWith(id: 20, dateModified: 0, dateAdded: 0, title: 'я (кириллица)', artist: '', album: ''),
          songWith(id: 18, dateModified: 0, dateAdded: 0, title: 'АА (кириллица)', artist: '', album: ''),
          songWith(id: 17, dateModified: 0, dateAdded: 0, title: 'А (кириллица)', artist: '', album: ''),
          songWith(id: 19, dateModified: 0, dateAdded: 0, title: 'а (кириллица)', artist: '', album: ''),
          songWith(id: 8, dateModified: 0, dateAdded: 0, title: 'z', artist: '', album: ''),
          songWith(id: 6, dateModified: 0, dateAdded: 0, title: 'AA', artist: '', album: ''),
          songWith(id: 5, dateModified: 0, dateAdded: 0, title: 'A', artist: '', album: ''),
          songWith(id: 7, dateModified: 0, dateAdded: 0, title: 'a', artist: '', album: ''),
          songWith(id: 0, dateModified: 0, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 1, dateModified: 1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 2, dateModified: -1, dateAdded: 0, title: '', artist: '', album: ''),
          songWith(id: 3, dateModified: 0, dateAdded: 1, title: '', artist: '', album: ''),
          songWith(id: 4, dateModified: 0, dateAdded: -1, title: '', artist: '', album: ''),
          songWith(id: 9, dateModified: 0, dateAdded: 0, title: '', artist: 'A', album: ''),
          songWith(id: 10, dateModified: 0, dateAdded: 0, title: '', artist: 'AA', album: ''),
          songWith(id: 11, dateModified: 0, dateAdded: 0, title: '', artist: 'a', album: ''),
          songWith(id: 12, dateModified: 0, dateAdded: 0, title: '', artist: 'z', album: ''),
          songWith(id: 21, dateModified: 0, dateAdded: 0, title: '', artist: 'А (кириллица)', album: ''),
          songWith(id: 22, dateModified: 0, dateAdded: 0, title: '', artist: 'АА (кириллица)', album: ''),
          songWith(id: 23, dateModified: 0, dateAdded: 0, title: '', artist: 'а (кириллица)', album: ''),
          songWith(id: 24, dateModified: 0, dateAdded: 0, title: '', artist: 'я (кириллица)', album: ''),
        ],
      },
    };
    for (final MapEntry(key: sortOrder, value: featureTestCases) in testCases.entries) {
      for (final MapEntry(key: feature, value: expectedContentList) in featureTestCases.entries) {
        test('Sorts songs by ${feature.name} ${sortOrder.name}', () async {
          expect(
            (songs.toList()..sort(SongSort(feature: feature, order: sortOrder).comparator)).map((song) => song.toMap()),
            expectedContentList.map((song) => song.toMap()),
          );
        });
      }
    }
  });

  group('Album sorting', () {
    late List<Album> albums;
    setUp(() {
      albums = [
        albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
        albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
        albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
        albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
        albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
        albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
      ];
    });
    final Map<SortOrder, Map<AlbumSortFeature, List<Album>>> testCases = {
      SortOrder.ascending: {
        AlbumSortFeature.title: [
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        ],
        AlbumSortFeature.artist: [
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
        ],
        AlbumSortFeature.year: [
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
        ],
        AlbumSortFeature.numberOfSongs: [
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
        ],
      },
      SortOrder.descending: {
        AlbumSortFeature.title: [
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
        ],
        AlbumSortFeature.artist: [
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
        ],
        AlbumSortFeature.year: [
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
        ],
        AlbumSortFeature.numberOfSongs: [
          albumWith(id: 23, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 1),
          albumWith(id: 17, album: '', artist: '', lastYear: 1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 20, album: '', artist: '', lastYear: null, firstYear: 1, numberOfSongs: 0),
          albumWith(id: 0, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 1, album: 'A', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 2, album: 'AA', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 3, album: 'a', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 4, album: 'z', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 5, album: 'А (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 6, album: 'АА (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 7, album: 'а (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 8, album: 'я (кириллица)', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 9, album: '', artist: 'A', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 10, album: '', artist: 'AA', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 11, album: '', artist: 'a', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 12, album: '', artist: 'z', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 13, album: '', artist: 'А (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 14, album: '', artist: 'АА (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 15, album: '', artist: 'а (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 16, album: '', artist: 'я (кириллица)', lastYear: 0, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 19, album: '', artist: '', lastYear: null, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 22, album: '', artist: '', lastYear: null, firstYear: null, numberOfSongs: 0),
          albumWith(id: 18, album: '', artist: '', lastYear: -1, firstYear: 0, numberOfSongs: 0),
          albumWith(id: 21, album: '', artist: '', lastYear: null, firstYear: -1, numberOfSongs: 0),
          albumWith(id: 24, album: '', artist: '', lastYear: 0, firstYear: 0, numberOfSongs: -1),
        ],
      },
    };
    for (final MapEntry(key: sortOrder, value: featureTestCases) in testCases.entries) {
      for (final MapEntry(key: feature, value: expectedContentList) in featureTestCases.entries) {
        test('Sorts albums by ${feature.name} ${sortOrder.name}', () async {
          expect(
            (albums.toList()..sort(AlbumSort(feature: feature, order: sortOrder).comparator))
                .map((album) => album.toMap()),
            expectedContentList.map((album) => album.toMap()),
          );
        });
      }
    }
  });

  group('Playlist sorting', () {
    late List<Playlist> playlists;
    setUp(() {
      playlists = [
        playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
        playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
        playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
        playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
        playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
        playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
        playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
        playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
        playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
        playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
        playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
        playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
        playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
        playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
      ];
    });
    final Map<SortOrder, Map<PlaylistSortFeature, List<Playlist>>> testCases = {
      SortOrder.ascending: {
        PlaylistSortFeature.dateModified: [
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
        ],
        PlaylistSortFeature.dateAdded: [
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
        ],
        PlaylistSortFeature.name: [
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
        ],
      },
      SortOrder.descending: {
        PlaylistSortFeature.dateModified: [
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
        ],
        PlaylistSortFeature.dateAdded: [
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
        ],
        PlaylistSortFeature.name: [
          playlistWith(id: 8, name: 'я (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 6, name: 'АА (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 5, name: 'А (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 7, name: 'а (кириллица)', dateModified: 0, dateAdded: 0),
          playlistWith(id: 4, name: 'z', dateModified: 0, dateAdded: 0),
          playlistWith(id: 2, name: 'AA', dateModified: 0, dateAdded: 0),
          playlistWith(id: 1, name: 'A', dateModified: 0, dateAdded: 0),
          playlistWith(id: 3, name: 'a', dateModified: 0, dateAdded: 0),
          playlistWith(id: 9, name: '', dateModified: 1, dateAdded: 0),
          playlistWith(id: 0, name: '', dateModified: 0, dateAdded: 0),
          playlistWith(id: 12, name: '', dateModified: 0, dateAdded: 1),
          playlistWith(id: 13, name: '', dateModified: 0, dateAdded: -1),
          playlistWith(id: 10, name: '', dateModified: -1, dateAdded: 0),
          playlistWith(id: 11, name: '', dateModified: null, dateAdded: 0),
        ],
      },
    };
    for (final MapEntry(key: sortOrder, value: featureTestCases) in testCases.entries) {
      for (final MapEntry(key: feature, value: expectedContentList) in featureTestCases.entries) {
        test('Sorts playlists by ${feature.name} ${sortOrder.name}', () async {
          expect(
            (playlists.toList()..sort(PlaylistSort(feature: feature, order: sortOrder).comparator))
                .map((playlist) => playlist.toMap()),
            expectedContentList.map((playlist) => playlist.toMap()),
          );
        });
      }
    }
  });

  group('Artist sorting', () {
    late List<Artist> artists;
    setUp(() {
      artists = [
        artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
        artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
        artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
        artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
        artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
      ];
    });
    final Map<SortOrder, Map<ArtistSortFeature, List<Artist>>> testCases = {
      SortOrder.ascending: {
        ArtistSortFeature.name: [
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
        ],
        ArtistSortFeature.numberOfAlbums: [
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
        ],
        ArtistSortFeature.numberOfTracks: [
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
        ],
      },
      SortOrder.descending: {
        ArtistSortFeature.name: [
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
        ],
        ArtistSortFeature.numberOfAlbums: [
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
        ],
        ArtistSortFeature.numberOfTracks: [
          artistWith(id: 11, artist: '', numberOfAlbums: 0, numberOfTracks: 1),
          artistWith(id: 8, artist: 'я (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 6, artist: 'АА (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 5, artist: 'А (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 7, artist: 'а (кириллица)', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 4, artist: 'z', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 2, artist: 'AA', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 1, artist: 'A', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 3, artist: 'a', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 0, artist: '', numberOfAlbums: 0, numberOfTracks: 0),
          artistWith(id: 9, artist: '', numberOfAlbums: 1, numberOfTracks: 0),
          artistWith(id: 10, artist: '', numberOfAlbums: -1, numberOfTracks: 0),
          artistWith(id: 12, artist: '', numberOfAlbums: 0, numberOfTracks: -1),
        ],
      },
    };
    for (final MapEntry(key: sortOrder, value: featureTestCases) in testCases.entries) {
      for (final MapEntry(key: feature, value: expectedContentList) in featureTestCases.entries) {
        test('Sorts artists by ${feature.name} ${sortOrder.name}', () async {
          expect(
            (artists.toList()..sort(ArtistSort(feature: feature, order: sortOrder).comparator))
                .map((artist) => artist.toMap()),
            expectedContentList.map((artist) => artist.toMap()),
          );
        });
      }
    }
  });
}
