// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM1R_dcMdHDIbdJ0aRlNhSIzfN6DTYayg',
    appId: '1:574502524315:android:b7be71579f4098be31fd3e',
    messagingSenderId: '574502524315',
    projectId: 'sweyer-def42',
    databaseURL: 'https://sweyer-def42.firebaseio.com',
    storageBucket: 'sweyer-def42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChInWRDse65X3YviyULeoi4FoXFP_a-o',
    appId: '1:574502524315:ios:6ec9eb013907ccb631fd3e',
    messagingSenderId: '574502524315',
    projectId: 'sweyer-def42',
    databaseURL: 'https://sweyer-def42.firebaseio.com',
    storageBucket: 'sweyer-def42.firebasestorage.app',
    androidClientId: '574502524315-hmfneng06499ct46kt68g5ttrf3p5dvl.apps.googleusercontent.com',
    iosBundleId: 'com.nt4f04und.sweyer',
  );
}
