/// Flutter icons SweyerIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class SweyerIcons {
  SweyerIcons._();

  static const _kFontFam = 'SweyerIcons';
  static const String? _kFontPkg = null;

  static const IconData play_next = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_to_queue = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
