package com.nt4f04uNd.player;

public class Constants {

   public static final String EVENT_CHANNEL_STREAM = "EVENT_CHANNEL_STREAM";
   public static final String PLAYER_CHANNEL_STREAM = "PLAYER_CHANNEL_STREAM";
   public static final String SONGS_CHANNEL_STREAM = "SONGS_CHANNEL_STREAM";

   // Events
   public static String EVENT_BECOME_NOISY = "com.nt4f04uNd.player.EVENT_BECAME_NOISY";

   public static String EVENT_NOTIFICATION_CHANNEL_ID = "com.nt4f04uNd.player.EVENT_NOTIFICATION_CHANNEL";
   public static String EVENT_NOTIFICATION_INTENT_PLAY = "com.nt4f04uNd.player.EVENT_NOTIFICATION_PLAY";
   public static String EVENT_NOTIFICATION_INTENT_PAUSE = "com.nt4f04uNd.player.EVENT_NOTIFICATION_PAUSE";
   public static String EVENT_NOTIFICATION_INTENT_NEXT = "com.nt4f04uNd.player.EVENT_NOTIFICATION_NEXT";
   public static String EVENT_NOTIFICATION_INTENT_PREV = "com.nt4f04uNd.player.EVENT_NOTIFICATION_PREV";

   // Player methods
   public static String PLAYER_METHOD_REQUEST_FOCUS = "PLAYER_METHOD_REQUEST_FOCUS";
   public static String PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_FAILED = "PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_FAILED";
   public static String PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_GRANTED = "PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_GRANTED";
   public static String PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_DELAYED = "PLAYER_METHOD_REQUEST_FOCUS_RETURN_AUDIOFOCUS_REQUEST_DELAYED";

   public static String PLAYER_METHOD_FOCUS_CHANGE = "PLAYER_METHOD_FOCUS_CHANGE";
   public static String PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_GAIN = "PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_GAIN";
   public static String PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS = "PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS";
   public static String PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS_TRANSIENT = "PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS_TRANSIENT";
   public static String PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK = "PLAYER_METHOD_FOCUS_CHANGE_ARG_AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK";

   public static String PLAYER_METHOD_HOOK_BUTTON_CLICK = "PLAYER_METHOD_HOOK_BUTTON_CLICK";

   public static String PLAYER_METHOD_ABANDON_FOCUS = "PLAYER_METHOD_ABANDON_FOCUS";

   public static String PLAYER_METHOD_INTENT_ACTION_VIEW = "PLAYER_METHOD_INTENT_ACTION_VIEW";

   public static String PLAYER_METHOD_NOTIFICATION_SHOW = "PLAYER_METHOD_NOTIFICATION_SHOW";
   public static String PLAYER_METHOD_NOTIFICATION_SHOW_ARG_TITLE = "PLAYER_METHOD_NOTIFICATION_SHOW_ARG_TITLE";
   public static String PLAYER_METHOD_NOTIFICATION_SHOW_ARG_ARTIST = "PLAYER_METHOD_NOTIFICATION_SHOW_ARG_ARTIST";
   public static String PLAYER_METHOD_NOTIFICATION_SHOW_ARG_ALBUM_ART_BYTES = "PLAYER_METHOD_NOTIFICATION_SHOW_ARG_ALBUM_ART_BYTES";
   public static String PLAYER_METHOD_NOTIFICATION_SHOW_ARG_IS_PLAYING = "PLAYER_METHOD_NOTIFICATION_SHOW_ARG_IS_PLAYING";

   public static String PLAYER_METHOD_NOTIFICATION_CLOSE = "PLAYER_METHOD_NOTIFICATION_CLOSE";

   // Songs methods
   public static String SONGS_METHOD_METHOD_SEND_SONGS = "SONGS_METHOD_METHOD_SEND_SONGS";
   public static String SONGS_METHOD_METHOD_RETRIEVE_SONGS = "SONGS_METHOD_METHOD_RETRIEVE_SONGS";
}