# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play Beta"
  lane :beta do |options|
    Dir.chdir ".." do
      v_flutter_version = flutter_version()
      version_code = v_flutter_version["version_code"]
      version_name = v_flutter_version["version_name"]

      upload_to_play_store(
        track: 'beta',
        version_code: version_code,
        package_name: options[:package_name],
        aab: options[:aab_path] || 'build/app/outputs/bundle/release/app-release.aab',
        skip_upload_screenshots: true,
        skip_upload_images: true,
        json_key: ENV["FASTLANE_ANDROID_JSON_KEY_FILE"]
      )
    end
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
