name: Update Goldens
on: 
  workflow_dispatch:
    inputs:
      commit:
        type: boolean
        default: true
        required: true
        description: Commit new Goldens to this branch.

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v5

      - name: 🧪 Test Sweyer
        uses: ./.github/workflows/test
        with:
          testing_arguments: --update-goldens

      - name: 📁 Save updated Golden test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golden-test-updated
          path: test/golden/goldens

      - name: 💾 Commit updated Golden test artifacts
        uses: stefanzweifel/git-auto-commit-action@v7
        if: github.event.inputs.commit == 'true'
        with:
          commit_message: 🤖 Update Golden test artifacts 🤖
